### ISSUE TITLE
State in localstorage

### ISSUE THREAD

**Issue by jondot** [howtographql/react-apollo#1]
Hi all,
Awesome work, just amazing the depth you went through with the tutorials and the website!

I have a small nit, based on something I battle with today in my own stuff - so I specifically looked for that, and here it was:

https://github.com/howtographql/react-apollo/blob/master/src/components/Header.js#L9

Isn't this not healthy in React in terms of state management? Why wouldn't it come from a request?

And the larger philosophical question is - I guess this is part of a "app and viewer related data", who's to fetch these (is that 'App' ?) ? and how can we guarantee that we fetch it at the right time and there's no app-wide stale data?

PS, for reference - here's some of that logic elsewhere: https://github.com/LIYINGZHEN/auth-graphql/blob/master/client/components/Header.js

**Comment by nikolasburk** [comment]
Hi @jondot, thanks a lot for the comment! You're definitely correct that this is not the ideal and most idiomatic way of handling authentication logic with React. It definitely has a couple of flaws, e.g. that essentially a user is always logged in as long as there is the `userId` in `localStorage` - even when the session token actually expires. In a real-world scenario, the info of a particular user being logged in or not should definitely be retrieved from the server (or cached in a more intelligent way). We chose this approach as it's slightly more instructive for the tutorial as our goal is to explain major GraphQL concepts and not deal too much in detail with other things. This is why we often took the "shortest path" instead of maybe the one that's appropriate for real world use cases. I'm not sure if we'll change this in the actual example project, but we should probably highlight this in the tutorial itself (feel free to create a PR about this as well).
