### ISSUE TITLE
Read everytime on render() from localStorage? Seriously? How to something like Redux Store with Apollo?

### ISSUE THREAD

**Issue by johnunclesam** [howtographql/react-apollo#18]
I see in https://github.com/howtographql/react-apollo/blob/master/src/components/Header.js you use:

`const userId = localStorage.getItem(GC_USER_ID)`

which seems to me a bit ugly: everytime `Header render()` is called you read from localStorage?

With `react-redux` I used to go with something like this:

```javascript
render() {
  const { authentication } = this.props;
  ...
}

const mapStateToProps = state => ({
  authentication: state.authentication
});

export default connect(mapStateToProps, { logoutAction })(Navbar);
```

And also if I read from localStorage on every `render()` and let's say I wanna store in localStorage all my user's data (eg. `{username: "john", age: "15"}`) when I pass this `const` to one of my children components everytime it re-render because the JSON.parse make it a new object! Everytime!

How to have something like a Redux Store with Apollo?

**Comment by johnunclesam** [comment]
Question on StackOverflow: https://stackoverflow.com/questions/47631443/accessing-apollo-store-like-i-used-to-go-with-redux-store

**Comment by nikolasburk** [comment]
Hey @johnunclesam, I agree that this definitely is not an elegant solution! However, since this tutorial is really focussed on GraphQL and using it from React & Apollo, we still chose to go with it to not add too much complexity for the other "layers" of the tutorial. 
Out of curiosity, do you have a better solution in mind? I'd be more than happy to merge a PR if you have a good idea of how this could be improved without creating too much distraction from the actual purpose of the tutorial 🙂
