### ISSUE TITLE
Tutorial refactor with new Apollo v2.1 declarative API

### ISSUE THREAD

**Issue by swcarlosrj** [howtographql/react-apollo#38]
Hi @nikolasburk ,

Couple days ago I finished refactoring this tutorial with new Apollo declarative API, also I've created branches with each step solution with both HOCs and component based API. In this way, user could decide which version to choose, even jump into diverse branches to check solutions and compare how it was implemented in the other version.

I think that could be interesting to debate about solutions adopted, so if you've a couple minutes, please, check the [repo](https://github.com/swcarlosrj/react-apollo) and raise as many issues you can 😛(don't try to use compare branches functionality, it doesn't work from now, just look into the branches code)

Actually, I'm working on the doc, hopefully, I'll have it finished next week. Btw, if you could create a new branch, I could do a pull request with final tutorial code with new Apollo API as you've in master, so we could review it from there too.

Congrats for the great tutorial, I've really enjoyed that's main reason why I've decided to refactor it because it get into Apollo essentials in an easy way, so hopefully there'll be another devs that they can learn from it.

Looking forward to hearing from you. Have a great day!

**Comment by aboglioli** [comment]
Thank you!

**Comment by nikolasburk** [comment]
Hey @swcarlosrj,

this is awesome 😄 We definitely want to update the tutorial to use Apollo's new render props API. Another big portion of the work will be to rewrite the actual [tutorial](https://www.howtographql.com/react-apollo/0-introduction/) since the two need to be in sync! If you're able to to update the tutorial as well, that would indeed be incredibly helpful 🙌 

I haven't checked out your repo in detail yet, hopefully I'll get to that over the next few days! By the way, are you on our [Slack](https://slack.graph.cool)? I'd say we continue the discussion there 🙂

**Comment by swcarlosrj** [comment]
@nikolasburk let's do it 🚀
