### ISSUE TITLE
if the order is in ASC or DESC the insert will be wrong.

### ISSUE THREAD

**Issue by lifeiscontent** [howtographql/react-apollo#60]
https://github.com/howtographql/react-apollo/blob/7dc3f55f2f79313cc61dff7a91450b5bc18e131f/src/components/CreateLink.js#L49-L62

apollo will throw an error if you've sorted the results in a different order and the cache hasn't been hit with the set order.

how would this be solved?

**Comment by swcarlosrj** [comment]
Thanks @lifeiscontent for opening this issue 😄. I think what you're trying to do is an extra feature that's not contemplated to not over complicate the tutorial. Closing this for now!

**Comment by lifeiscontent** [comment]
@swcarlosrj sure, but at the same time I'm legitimately asking how is this done? Because currently there are no docs that cover this kind of case. I don't think this should be closed. 👎

**Comment by swcarlosrj** [comment]
@lifeiscontent thanks for getting back on this. I think this is not an issue, in fact it's a feature that's why I've closed it. Of course you could always ask how is being done but unfortunately I cannot answer to such core functionality. I'd def suggest you to contact with someone from the Apollo team, they'll probably help you on this!

**Comment by lifeiscontent** [comment]
@swcarlosrj not to be salty about it, but literally every issue I've ever opened on any apollo project goes unanswered. 👎

**Comment by swcarlosrj** [comment]
@lifeiscontent you're totally right, sorry about that! I guess that we could improve the existing tutorials but they'll eventually be outdated, idk if you've already seen [this issue](https://github.com/howtographql/howtographql/issues/896) but in order to invest time on this, we should have a robust platform where we could freely & do an efficient work. Hopefully it'll happen soon 🤞, thanks for the feedback!
