### ISSUE TITLE
Error due to missing createdAt in type Link of hn-starter.graphql schema

### ISSUE THREAD

**Issue by gyaresu** [howtographql/react-apollo#7]
The React + Apollo Tutorial: https://www.howtographql.com/react-apollo/2-queries-loading-links/ Errors due to https://graphqlbin.com/hn-starter.graphql missing field `createdAt` in `Link` @nikolasburk 

Not sure how you want to deal with this.

It is a really great tutorial so far and I enjoyed finding why the code kept throwing an error!

p.s. The graphcool instance of graphiql helped me find the error

```
query AllLinksQuery {
  allLinks {
    id
    createdAt
    url
    description
  }
}
```

```
{
  "data": null,
  "errors": [
    {
      "message": "Cannot query field 'createdAt' on type 'Link'. (line 21, column 5):\n    createdAt\n    ^",
      "locations": [
        {
          "line": 21,
          "column": 5
        }
      ]
    }
  ]
}
```

**Comment by nikolasburk** [comment]
Hey @gyaresu! Sorry, we just made a change to our system yesterday and didn't update the tutorial accordingly yet. 

The problem is that the original schema (stored [here](https://graphqlbin.com/hn-starter.graphql)) you used to create the Graphcool project looked like this:

```graphql
type Link {
  id: ID! @isUnique
  url: String!
  description: String!
}
```

Before the change in our system, `createdAt` and `updatedAt` always were required fields. So despite the fact that they were not explicitly added to the `Link` type, our system would still and and manage them for you. This is not the case any more. If you now want to use these fields, you need to explicitly add them to your types!

I just updated the starter schema to include these fields on the `Link` type:

```graphql
type Link {
  id: ID! @isUnique
  createdAt: DateTime!
  updatedAt: DateTime!
  url: String!
  description: String!
}
```

There are two ways for you to fix the issue now:

1. Recreate the whole project with `graphcool init --schema https://graphqlbin.com/hn-starter.graphql` (which now includes these fields)
2. Update the `Link` type in your current project by adding the `createdAt` and `updatedAt` to your `project.graphcool` and run `graphcool push` in the terminal

**Comment by han-so1omon** [comment]
Just a note. I'm going through this tutorial now. The step: *Writing the GraphQL query* on part *Queries: Loading Links* on tutorial *Fetching Data using GraphQL Queries* does not run. It is required to add a `createdAt: String!` element to the `type Link` in `.../src/schema.graphql`
